-- Create hotels table if it doesn't exist
CREATE TABLE IF NOT EXISTS hotels (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500),
    city VARCHAR(100),
    country VARCHAR(100),
    postal_code VARCHAR(20),
    phone VARCHAR(50),
    email VARCHAR(255),
    website VARCHAR(255),
    star_rating INTEGER CHECK (star_rating >= 1 AND star_rating <= 5),
    description TEXT,
    amenities TEXT[],
    room_count INTEGER,
    price_per_night DECIMAL(10, 2),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert dummy hotel data
INSERT INTO hotels (
    name, address, city, country, postal_code, phone, email, website,
    star_rating, description, amenities, room_count, price_per_night,
    latitude, longitude
) VALUES 
(
    'Grand Palace Hotel',
    '123 Main Street',
    'New York',
    'USA',
    '10001',
    '+1-555-0123',
    'info@grandpalace.com',
    'https://www.grandpalace.com',
    5,
    'A luxurious 5-star hotel in the heart of Manhattan with stunning city views and world-class amenities.',
    ARRAY['WiFi', 'Pool', 'Spa', 'Gym', 'Restaurant', 'Room Service', 'Concierge'],
    250,
    299.99,
    40.7589, 
    -73.9851
),
(
    'Sunset Beach Resort',
    '456 Ocean Drive',
    'Miami',
    'USA',
    '33139',
    '+1-555-0456',
    'reservations@sunsetbeach.com',
    'https://www.sunsetbeachresort.com',
    4,
    'Beachfront resort with panoramic ocean views, perfect for relaxation and water activities.',
    ARRAY['WiFi', 'Beach Access', 'Pool', 'Restaurant', 'Bar', 'Water Sports'],
    180,
    189.99,
    25.7617,
    -80.1918
),
(
    'Mountain View Lodge',
    '789 Alpine Way',
    'Denver',
    'USA',
    '80202',
    '+1-555-0789',
    'stay@mountainview.com',
    'https://www.mountainviewlodge.com',
    3,
    'Cozy mountain lodge offering breathtaking views of the Rocky Mountains and outdoor adventures.',
    ARRAY['WiFi', 'Hiking Trails', 'Restaurant', 'Fireplace', 'Parking'],
    75,
    129.99,
    39.7392,
    -104.9903
),
(
    'City Center Business Hotel',
    '321 Business Boulevard',
    'Chicago',
    'USA',
    '60601',
    '+1-555-0321',
    'business@citycenter.com',
    'https://www.citycenterbusiness.com',
    4,
    'Modern business hotel located in downtown Chicago, ideal for corporate travelers.',
    ARRAY['WiFi', 'Business Center', 'Gym', 'Restaurant', 'Meeting Rooms', 'Airport Shuttle'],
    200,
    169.99,
    41.8781,
    -87.6298
),
(
    'Boutique Garden Inn',
    '654 Garden Lane',
    'San Francisco',
    'USA',
    '94102',
    '+1-555-0654',
    'hello@boutiquegarden.com',
    'https://www.boutiquegarden.com',
    4,
    'Charming boutique hotel with beautiful gardens and personalized service in San Francisco.',
    ARRAY['WiFi', 'Garden', 'Restaurant', 'Pet Friendly', 'Bike Rental'],
    45,
    249.99,
    37.7749,
    -122.4194
),
(
    'Historic Downtown Hotel',
    '987 Heritage Street',
    'Boston',
    'USA',
    '02108',
    '+1-555-0987',
    'info@historicdowntown.com',
    'https://www.historicdowntown.com',
    3,
    'A beautifully restored historic hotel in the heart of Bostons historic district.',
    ARRAY['WiFi', 'Historic Tours', 'Restaurant', 'Library', 'Valet Parking'],
    120,
    179.99,
    42.3601,
    -71.0589
),
(
    'Lakeside Retreat',
    '147 Lakeshore Drive',
    'Seattle',
    'USA',
    '98101',
    '+1-555-0147',
    'retreat@lakeside.com',
    'https://www.lakesideretreat.com',
    4,
    'Peaceful lakeside hotel offering stunning water views and outdoor recreational activities.',
    ARRAY['WiFi', 'Lake Access', 'Kayak Rental', 'Restaurant', 'Spa', 'Hiking'],
    90,
    199.99,
    47.6062,
    -122.3321
),
(
    'Desert Oasis Resort',
    '258 Desert Road',
    'Phoenix',
    'USA',
    '85001',
    '+1-555-0258',
    'oasis@desert.com',
    'https://www.desertoasis.com',
    5,
    'Luxury desert resort featuring world-class spa treatments and championship golf course.',
    ARRAY['WiFi', 'Golf Course', 'Spa', 'Pool', 'Tennis Court', 'Restaurant', 'Bar'],
    300,
    349.99,
    33.4484,
    -112.0740
),
(
    'Coastal Inn',
    '369 Coastal Highway',
    'San Diego',
    'USA',
    '92101',
    '+1-555-0369',
    'stay@coastalinn.com',
    'https://www.coastalinn.com',
    3,
    'Affordable coastal inn with easy beach access and family-friendly amenities.',
    ARRAY['WiFi', 'Beach Access', 'Pool', 'Restaurant', 'Family Rooms'],
    80,
    149.99,
    32.7157,
    -117.1611
),
(
    'Urban Loft Hotel',
    '741 Metropolitan Ave',
    'Portland',
    'USA',
    '97201',
    '+1-555-0741',
    'loft@urban.com',
    'https://www.urbanloft.com',
    4,
    'Contemporary urban hotel featuring modern loft-style rooms in trendy Portland.',
    ARRAY['WiFi', 'Rooftop Bar', 'Gym', 'Restaurant', 'Art Gallery', 'Bike Storage'],
    65,
    219.99,
    45.5152,
    -122.6784
),
(
    'Royal Castle Hotel',
    '852 Castle Street',
    'Edinburgh',
    'Scotland',
    'EH1 2NG',
    '+44-131-555-0852',
    'royal@castle.com',
    'https://www.royalcastle.com',
    5,
    'Magnificent castle hotel overlooking Edinburgh with regal accommodations and fine dining.',
    ARRAY['WiFi', 'Castle Tours', 'Fine Dining', 'Spa', 'Library', 'Valet Service'],
    100,
    399.99,
    55.9533,
    -3.1883
),
(
    'Alpine Chalet',
    '963 Mountain Path',
    'Zurich',
    'Switzerland',
    '8001',
    '+41-44-555-0963',
    'chalet@alpine.com',
    'https://www.alpinechalet.com',
    4,
    'Traditional Swiss chalet hotel offering authentic Alpine experience with mountain views.',
    ARRAY['WiFi', 'Ski Storage', 'Restaurant', 'Sauna', 'Mountain Guides', 'Fireplace'],
    40,
    279.99,
    47.3769,
    8.5417
),
(
    'Tropical Paradise Resort',
    '159 Paradise Beach',
    'Cancun',
    'Mexico',
    '77500',
    '+52-998-555-0159',
    'paradise@tropical.com',
    'https://www.tropicalparadise.com',
    5,
    'All-inclusive tropical resort with pristine beaches and unlimited dining options.',
    ARRAY['WiFi', 'All Inclusive', 'Beach Access', 'Multiple Pools', 'Water Sports', 'Spa', 'Bars'],
    400,
    449.99,
    21.1619,
    -86.8515
),
(
    'Business Express Hotel',
    '753 Airport Road',
    'Atlanta',
    'USA',
    '30309',
    '+1-555-0753',
    'express@business.com',
    'https://www.businessexpress.com',
    3,
    'Convenient airport hotel perfect for business travelers with shuttle service.',
    ARRAY['WiFi', 'Airport Shuttle', 'Business Center', 'Gym', '24/7 Reception'],
    150,
    119.99,
    33.7490,
    -84.3880
),
(
    'Vineyard Estate Hotel',
    '864 Vineyard Lane',
    'Napa',
    'USA',
    '94558',
    '+1-555-0864',
    'estate@vineyard.com',
    'https://www.vineyardestate.com',
    5,
    'Luxury vineyard hotel offering wine tasting experiences and gourmet dining.',
    ARRAY['WiFi', 'Wine Tasting', 'Restaurant', 'Spa', 'Pool', 'Vineyard Tours'],
    60,
    599.99,
    38.2975,
    -122.2869
);